# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/ubuntu-16.04"  #<--16.04 LTS
  config.vm.provider "virtualbox" do |v|
    v.memory = 2028
    v.cpus = 2
    v.customize ["modifyvm", :id, "--usb", "on"]
    v.customize ["modifyvm", :id, "--usbehci", "on"]
    v.customize ["usbfilter", "add", "0",
      "--target", :id,
      "--name", "iOS",
      "--manufacturer", "Apple Inc.",
      "--product", "iPhone"]
    v.customize ["usbfilter", "add", "1",
      "--target", :id,
      "--name", "Android",
      "--manufacturer", "SAMSUNG",
      "--product", "SAMSUNG_Android"]
    v.gui = true
  end
end
